version: '3.8'

services:
  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=mydatabase

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ''
      ME_CONFIG_MONGODB_ADMINPASSWORD: ''
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo

  mongo_seed:
    build: ./mongo-seed
    links:
      - mongo

  server:
    image: nodejs
    build: ./server
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server
      - /server/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - PORT=8000
    depends_on:
      - mongo
    command:  node server.js

volumes:
  mongo-data:
